# Generated by Django 4.2 on 2025-11-26 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('short_uuid', models.CharField(editable=False, max_length=22, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_transcript', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('short_uuid', models.CharField(editable=False, max_length=22, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='captures/%Y/%m/%d/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('captured_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='captures.captureditem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='captureditem',
            index=models.Index(fields=['owner', '-created_at'], name='captures_ca_owner_i_b77036_idx'),
        ),
        migrations.AddIndex(
            model_name='captureditem',
            index=models.Index(fields=['owner', 'is_complete'], name='captures_ca_owner_i_585cde_idx'),
        ),
        migrations.AddIndex(
            model_name='capturedimage',
            index=models.Index(fields=['captured_item', 'order'], name='captures_ca_capture_10b7d2_idx'),
        ),
    ]
