---
- hosts: schmango
  become: true
  gather_facts: true

  vars_files:
    - vars/vars.yml
    - vars/secrets.yml

  tasks:
  - name: Install prerequisites for Docker
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present
      update_cache: yes

  - name: Create /etc/apt/keyrings for Docker GPG
    file:
      path: /etc/apt/keyrings
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
      state: present
      filename: docker

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Docker engine and related packages
    apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      state: latest

  - name: Ensure docker-compose-plugin is not installed
    apt:
      name: docker-compose-plugin
      state: absent

  - name: Install docker-compose-v2
    apt:
      name: docker-compose-v2
      state: present

  - name: Ensure Docker service is enabled and started
    service:
      name: docker
      enabled: yes
      state: started

  - name: Add application user to docker group
    user:
      name: "{{ app_user }}"
      groups: docker
      append: yes

  - name: Create application directory
    file:
      path: "{{ app_dir }}"
      state: directory
      owner: "{{ app_user }}"
      group: "{{ app_user }}"
      mode: '0755'

  - name: Create .env file
    template:
      src: templates/env.j2
      dest: "{{ app_dir }}/.env"
      owner: "{{ app_user }}"
      group: "{{ app_user }}"
      mode: '0600'