---
- hosts: deployment
  become: true
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:
    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Create .env file
      template:
        src: templates/env.j2
        dest: "{{ app_dir }}/.env"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0600'

    - name: Display generated credentials
      debug:
        msg:
          - "Database password: {{ db_password }}"
          - "Secret key: {{ secret_key }}"
          - "Allowed hosts: {{ allowed_hosts }}"