---
app_dir: /opt/myapp
app_user: "devops"
db_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
secret_key: "{{ lookup('password', '/dev/null length=50 chars=ascii_letters,digits') }}"
allowed_hosts: "{{ ansible_default_ipv4.address }},localhost,127.0.0.1"